theme: minima


header_pages:
  - about.md

minima:
  date_format: "%b %-d, %Y"


title: Sci-Hook
author: Nikita Klyuchnikov
email: fmsnew@gmail.com
github_username: fmsnew
description: > #
  Tool for scientific analytics and search: reference manager, citation-graph visualization, and literature recommender system.
