theme: minima

title: SciGraphVis
author: Nikita Klyuchnikov
github_username:  fmsnew
description: > #
  Tool for scientific analytics: reference manager, visualization tool, and literature recommender system.